services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: broker
    environment:
      # Singe-node KRaft cluster kettős szereppel: broker és controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Három listener: EXTERNAL a host géphez, CLIENT a Docker hálózaton belül, CONTROLLER KRaft controller
      # CLIENT a Kafdrop számára
      KAFKA_LISTENERS: EXTERNAL://:9092,CLIENT://:9093,CONTROLLER://:9094
      # Broker által visszamondott címek, amin elérhető (EXTERNAL a host géphez, CLIENT a Docker hálózaton belül)
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,CLIENT://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
  kafdrop:
    image: obsidiandynamics/kafdrop:4.2.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - "kafka"